import "./globals.css";

import ToasterProvider from "@/components/provider/ToasterProvider";
import ReactQueryProvider from "@/components/provider/ReactQueryProvider";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <ClerkProvider>
         <ReactQueryProvider>
            <html lang="en">
               <body>
                  <ToasterProvider />
                  {children}
               </body>
            </html>
         </ReactQueryProvider>
      </ClerkProvider>
   );
}
